### ISSUE TITLE
Support for full-color (24-bit) graphics

### ISSUE THREAD

**Issue by n8willis** [orakaro/rainbowstream#206]
The terminal image viewer could support 24-bit color graphics for a fairly noticeable quality improvement.

Using something like timg, for example (https://github.com/hzeller/timg)

Attached is a side-by-side example; timg showing the photo on the left vs rainbowstream's built-in viewer on the right, as close to the same size as I could make them.
![timg-vs-rainbowstream](https://cloud.githubusercontent.com/assets/2192132/20576045/fe62bde8-b1b3-11e6-982c-a535054d4bcc.png)

**Comment by DTVD** [comment]
Nice proposal - added in TODO list - thanks

**Comment by Nefari0uss** [comment]
Is there any way to show true color images in the way [ranger] does?

[ranger]: https://github.com/ranger/ranger/wiki/Image-Previews

**Comment by borysn** [comment]
ranger uses `w3m-img` to display images in the console. quite successfully too. it's a good proposal I think. I was coming to suggest that.

**Comment by Nefari0uss** [comment]
@borysn I've fixed the imgur link I've attached. 

Scaling images is probably not a bad idea. Maybe imagemagicks/graphicsmagicks?

**Comment by borysn** [comment]
@Nefari0uss i'd say imagemagick ftw, but it's not my project

**Comment by n8willis** [comment]
Rainbowstream can already scale images with the `IMAGE_RESIZE_TO_FIT` directive. How is what you're describing with imagemagick different from that?

**Comment by Nefari0uss** [comment]
It'll generate a new image resized to the given dimensions. If Rainbowstream already has it then ignore my remarks concerning image/graphicks magicks packages.

**Comment by ryanwilliams** [comment]
Maybe I'm misunderstanding, but `config 24BIT = true` enables true colour images for me.

**Comment by borysn** [comment]
@ryanwilliams i don't see 24BIT as a config option?

@n8willis this doesn't seem to work for me, the images are not resized, and they are still extremely low quality. using something like w3m-img or maybe resizing with imagemagick would be a better solution?

**Comment by ryanwilliams** [comment]
@borysn It doesn't seem to be documented, but it's working fine for me. I found it by looking at the code:  https://github.com/DTVD/rainbowstream/search?utf8=%E2%9C%93&q=24bit

**Comment by borysn** [comment]
@ryanwilliams i gotcha, yea it's working, just makes image viewing even worse

**Comment by ryanwilliams** [comment]
@borysn Not sure how it makes it worse, looks pretty nice to me: 
![cute-rainbowstream](https://cloud.githubusercontent.com/assets/1215/23097939/8a809548-f6a6-11e6-9668-b479d21a9daa.png)

**Comment by jlozadad** [comment]
what is the status with this?

**Comment by danger89** [comment]
I think this has never been merged nor integrated, really a shame..!

**Comment by slarrain** [comment]
Other projects, like [YTFZF](https://github.com/pystardust/ytfzf) are using [ueberzug](https://github.com/seebye/ueberzug) and the thumbnails of YT videos look pretty nice on the terminal. Maybe something like this could be implemented?

**Comment by orakaro** [comment]
Rainbowstream can run with 24 bit, by either starting with `rainbowstream -24` or using the hidden config of `24BIT` above
