### ISSUE TITLE
You should upgrade with pip install -U rainbowstream

### ISSUE THREAD

**Issue by plgrazon** [orakaro/rainbowstream#266]
Hi good day everyone I see this every time I rainbowstream. I tried running the command in sudo but it says Requirement already up-to-date  and requirement not upgraded as not directly required.

**Comment by Nikorasu** [comment]
This has been driving me nuts too, I wanna upgrade to 1.3.8 lol.
Just fyi, the dev (orakaro) replied to a similar post just the other day, that he was looking into fixing this. Seems the upload for 1.3.8 failed last time.
https://github.com/orakaro/rainbowstream/issues/260#issuecomment-410525304

**Comment by orakaro** [comment]
Version 1.3.9 is up and this should be fine now

**Comment by plgrazon** [comment]
Thank you so much @orakaro! Everything works now :) I'll be closing this now
