### ISSUE TITLE
Twitter API changes

### ISSUE THREAD

**Issue by xxKeith20xx** [orakaro/rainbowstream#271]
We have connection problem with twitter stream API right now :(
The Site Streams and User Streams endpoints have been turned off. Please migrate to alternate APIs. See https://t.co/usss

So... is that the end for apps like this? ;c

**Comment by jokebroker** [comment]
looks like it :(

**Comment by yipmanfan** [comment]
I don't wish to over dramatize the situation but it feels like I have just been kicked in the CLI.

**Comment by johnpiers** [comment]
So is this the end of that? I can't believe that they would just do this, are there no alternatives?

**Comment by xxKeith20xx** [comment]
Not a solution but might Mastodon has some command line apps that are in active development: https://github.com/ihabunek/toot .

**Comment by mikeofmany** [comment]
I suppose if someone is up for refactoring the api calls,  https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/api-reference/site-stream

**Comment by cirrusUK** [comment]
a couple CLI alternatives which work for now at least..
   https://github.com/bear/python-twitter
   https://github.com/piroor/tweet.sh
   https://github.com/oysttyer/oysttyer

**Comment by orakaro** [comment]
The account activity now is premium or business only, and the subscription price is just ridiculous. More info here:
https://twitter.com/orakaro/status/1030785576973217792

Basically it is impossible for an opensource project.

Right now we can still use RS as a commandline client, but the stream need to be reconsidered carefully. Sorry about all of this.

**Comment by movalex** [comment]
Is it possible to force RS to automatically refresh timeline every, say, minute or so? Realtime streaming is not that important afterall. Also we can change the name to just Rainbow :)

**Comment by johnpiers** [comment]
Anything further on a workaround or plan of action? Is this dead in the water and if so, what alternatives, if any? Thanks.

**Comment by IngwiePhoenix** [comment]
See the link about the Twitter API that has been posted here and shown in the console too. Twitter "gracefuly" disabled streaming APIs - so even if there were alternatives, well, then there "were" alternatives. With the streaming API gone, all we can do is set a refresh time - and thats it.

**Comment by movalex** [comment]
Is it possible to set auto-refresh time in current version? I'd like it to refresh every minute, and preferably with no warnings from Twitter about Site Streams have been turned off.

> See the link about the Twitter API that has been posted here and shown in the console too. Twitter "gracefuly" disabled streaming APIs - so even if there were alternatives, well, then there "were" alternatives. With the streaming API gone, all we can do is set a refresh time - and thats it.

**Comment by ListeningGarden** [comment]
I've been curious if this is the reason why i'm unable to run rainbowstream via the command alone. Whenever I enter 'rainbowstream', it returns the following

> You are running latest version (1.4.0)
> 
> We have connection problem with twitter REST API right now :(
> Rate limit exceeded

I thought this may have been related to generating a new authentication, but is has persisted each time I have tried launching or reinstalling/re-authenticating over multiple days. Is there a specific command I have to use to launch now that the old API is dead? I couldn't get any like 'home' to work as rainbowstream fails to load and returns me to the zsh prompt after that message.

**Comment by jagarcia-stratio** [comment]
> 
> 
> I've been curious if this is the reason why i'm unable to run rainbowstream via the command alone. Whenever I enter 'rainbowstream', it returns the following
> 
> > You are running latest version (1.4.0)
> > We have connection problem with twitter REST API right now :(
> > Rate limit exceeded
> 
> I thought this may have been related to generating a new authentication, but is has persisted each time I have tried launching or reinstalling/re-authenticating over multiple days. Is there a specific command I have to use to launch now that the old API is dead? I couldn't get any like 'home' to work as rainbowstream fails to load and returns me to the zsh prompt after that message.
> 
> Can make a separate issue if this is unrelated, but seeing as how others may still be able to use theirs I wondered if it had any relation to the API switch.

I'm interested in the answer too xD

**Comment by itpropaul** [comment]
As a holdover for those of us that can't use rainbowstream to stream our twitter timelines to the terminal: https://www.howtogeek.com/117306/how-to-follow-a-twitter-feed-in-your-rss-reader/

**Comment by silvernode** [comment]
This is sad

**Comment by jeromewoody** [comment]
So if I'm following what's going on correctly, Twitter discontinued the
"stream" APIs, but the REST based  APIs are still accessible. If true and
the lack of the stream APIs are just the reality of things now, shouldn't
the focus going forward be connecting the client to the available APIs and
moving from a stream experience to a interval based "polling" experience.
I will morn the loss of real time updates and curse Twitter for removing
them, but I think rainbowstream is still a valuable enough command line
tool to just abandon. The patient can still be saved!

**Comment by karel-3d** [comment]
RIP

**Comment by karel-3d** [comment]
Nobody seems to be working on that.

**Comment by cirrusUK** [comment]
[bitlbee's twitter](https://wiki.bitlbee.org/HowtoTwitter/StreamDeprecation) is not too shabby 
*New tweets will only be shown once every 60 seconds

**Comment by tankred** [comment]
plz let the rainbow stream again

**Comment by deepcell** [comment]
R.I.P. this is bad joke!

**Comment by NickyTope** [comment]
@orakaro I am considering rewriting this myself to use polling, would like to know your opinion on it first though as it obviously breaks the whole streaming concept idea behind rainbowstream.. please let us know if you plan to support this product in the future !?

**Comment by orakaro** [comment]
Sorry for so late reply. Yes I will definitely appreciate someone can make polling happens. Just send PR!

**Comment by johnpiers** [comment]
So anything further, or is this the end of Rainbowstream? Sorry to bump this.

**Comment by jeromewoody** [comment]
I'm currently looking into this, I assume otheras are as well. If I get anywhere I'll send a PR.

**Comment by threecleartones** [comment]
So depressing to google "twitter linux terminal clients", come across rainbowstream, get excited by all the great reviews, follow the instructions (spent extra time resolving the missing .rainbow_config.json issue), running the app, getting excited by the interface, getting the "connection problem with API now" error, googling that, and only coming across this thread at the end of that whole process. Would be AWESOME to have the current status (and maybe a link to this thread) here:
https://github.com/orakaro/rainbowstream

and maybe here:
https://rainbowstream.readthedocs.io/en/latest/

I'm so excited by this project, I'll be watching this space for updates! 🤞

**Comment by deepcell** [comment]
You are not the only one, I spent hours to setup it with my custom
linux and then I got the very same warning from Twitter API.
Hopefully `rainbowstream` will reborn from ashes soon! ;D

On 3/9/19, Jeff Beam <notifications@github.com> wrote:
> So depressing to google "twitter linux terminal clients", come across
> rainbowstream, get excited by all the great reviews, follow the instructions
> (spent extra time resolving the missing .rainbow_config.json issue), running
> the app, getting excited by the interface, getting the "connection problem
> with API now" error, googling that, and only coming across this thread at
> the end of that whole process. Would be AWESOME to have the current status
> (and maybe a link to this thread) here:

> https://github.com/orakaro/rainbowstream

>

> and maybe here:

> https://rainbowstream.readthedocs.io/en/latest/

>

> I'm so excited by this project, I'll be watching this space for updates!
> 🤞

>

> --

> You are receiving this because you commented.

> Reply to this email directly or view it on GitHub:

> https://github.com/orakaro/rainbowstream/issues/271#issuecomment-471043710


-- 
PGP Key ID: 0x3F75FA35

**Comment by orakaro** [comment]
@threecleartones @deepcell Really sorry about that. Updated README 🙇

**Comment by johnpiers** [comment]
So, approaching 10 months since Rainbowstream lost it's ability to update itself realtime, is anything further going to transpire or is this truly dead in the water? Thanks.

**Comment by MystikSpiral** [comment]
Sounds like it's officially dead to me which is sad. 
I might be wrong but it looks like Twitter is wanting to charge for API access for certain things now which would mean Rainbowstream would no longer be free.

I wish they would just put a bullet through it's head already instead of keeping us holding on. 

It was the best twitter client hands down no matter what platform/OS you used.

**Comment by silvernode** [comment]
I say that Rainbowstream should rebrand and Target open alternatives to
Twitter like Mastodon and stop relying on centralized services like Twitter
that tend to change their mind on a dime. I think that's the only way to
keep this project somewhat alive.

**Comment by StarlitGhost** [comment]
@silvernode that already exists as tootstream, which was inspired by rainbowstream https://github.com/magicalraccoon/tootstream

**Comment by silvernode** [comment]
Yeah, I use tootstream though I still like Rainbowstream much better
because of the UX which is not exactly the same as tootstream.

**Comment by orakaro** [comment]
Hello guys, here is a good news: I succeed in an attemp to make RainbowStream's stream live again using a polling strategy! Here is some notes

* Live again from version 1.5.0
* It currently using a polling to `home` each 90 seconds. The Rate Limit for `home` command itseld is 15 times per 15 minutes. This 90 seconds is not configurable yet
* I also fixed direct messages. It was broken due to Twitter API Spec changes
* There is a problem with positions calculation in terminal colors and Readline. It reproduces in my Python 3.7.4 environment

**Comment by orakaro** [comment]
Let's consider this as a beta state. Please report any bug/problem 🙏

**Comment by johnpiers** [comment]
Awesome news.

**Comment by xxKeith20xx** [comment]
Works great!

**Comment by rek** [comment]
So amazing! Thanks!!

**Comment by yipmanfan** [comment]
Thanks.  It is working just great.  I actually prefer that it is not updating the stream in real-time.  It is much more readable during periods of high activity.

**Comment by vk0xOrg** [comment]
I'm getting 'Rate limit exceeded'. It even hasn't started in the first place.
![Screenshot at 2020-04-27 20-47-21](https://user-images.githubusercontent.com/45686717/80403611-8be37d80-88c8-11ea-9a03-b85fe40c3b49.png)

**Comment by HaxNet** [comment]
i am having the same problem...rate limit exceeded

**Comment by brfid** [comment]
Also getting rate limit exceeded

**Comment by cyrixhero** [comment]
Great Work!!

**Comment by guslanzetta1** [comment]
still having this problem
