### ISSUE TITLE
User message API

### ISSUE THREAD

**Issue by stan1slas** [orakaro/rainbowstream#274]
It looks like the command `inbox` or other commands from the category `messages` does not work anymore because of the very recent changes of the twitter API (17 september 2018) regarding the `Direct message endpoints`. [Here](https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/guides/direct-message-migration.html) are some informations

**Comment by nstr10** [comment]
API changes are being discussed in #271

**Comment by orakaro** [comment]
Fixed in 1.5.0
