### ISSUE TITLE
Rainbowstream

### ISSUE THREAD

**Issue by arlidge** [orakaro/rainbowstream#277]
Hi there, I get this 

Hi there! We're gonna get you all set up to use Rainbow Stream.
There seems to be a connection problem.
You might want to check your proxy settings (host, port and type)!

And that is all. It does not ask for setup or Auth. I am using the virtualenv python3 method for installation. I have no network issues and I don't have a proxy in use.  Mac OS Sierra

regards

**Comment by deepcell** [comment]
see the other issues, the problem is with twitter API.
