### ISSUE TITLE
"Sorry, image link is broken" on all images attempted

### ISSUE THREAD

**Issue by ftw37** [orakaro/rainbowstream#41]
Every time an image is in a tweet, I get a "Sorry, image link is broken" instead of the inline image.

config
  HEARTBEAT_TIMEOUT: 120
  IMAGE_ON_TERM: True
  THEME: monokai
  ASCII_ART: True
  HIDE_PROMPT: True
  PREFIX: @ftw
  SEARCH_MAX_RECORD: 5
  HOME_TWEET_NUM: 5
  RETWEETS_SHOW_NUM: 5
  QUOTE_FORMAT: #comment RT #owner: #tweet
  MESSAGES_DISPLAY: 5
  TREND_MAX: 10
  LIST_MAX: 5
  HISTORY_FILENAME: completer.hist
  IMAGE_SHIFT: 2
  IMAGE_MAX_HEIGHT: 90
  USER_DOMAIN: userstream.twitter.com
  PUBLIC_DOMAIN: stream.twitter.com
  SITE_DOMAIN: sitestream.twitter.com

**Comment by fowlslegs** [comment]
I'm having the same issue w/ Ubuntu 14.04 and Python 3.4.0. I your fix from Aug. 20th, however, it seems that  PIL is no longer an available Python package: "Could not find any downloads that satisfy the requirement PIL."

Traceback is pretty much the same.
