### ISSUE TITLE
MAC 10.10.1 Error Startup.

### ISSUE THREAD

**Issue by limeless** [orakaro/rainbowstream#83]
First of all thanks for the awesome work!
but I got some error and I can't figure out what Im doing wrong.
## I got this problem after Ive done the virtualenv install.

$ rainbowstream
Traceback (most recent call last):
  File "/Users/z3roblock/venv/bin/rainbowstream", line 9, in <module>
    load_entry_point('rainbowstream==1.2.5', 'console_scripts', 'rainbowstream')()
  File "/Users/z3roblock/venv/lib/python2.7/site-packages/pkg_resources/**init**.py", line 474, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/z3roblock/venv/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2582, in load_entry_point
    return ep.load()
  File "/Users/z3roblock/venv/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2265, in load
    return self._load()
  File "/Users/z3roblock/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2268, in _load
    module = __import__(self.module_name, fromlist=['**name**'], level=0)
  File "/Users/z3roblock/venv/lib/python2.7/site-packages/rainbowstream/rainbow.py", line 22, in <module>
    from .draw import *
  File "/Users/z3roblock/venv/lib/python2.7/site-packages/rainbowstream/draw.py", line 15, in <module>
    from .c_image import *
  File "/Users/z3roblock/venv/lib/python2.7/site-packages/rainbowstream/c_image.py", line 24, in <module>
    rgb2short = call_c()
  File "/Users/z3roblock/venv/lib/python2.7/site-packages/rainbowstream/c_image.py", line 19, in call_c
    assert os.system(build + " >/dev/null 2>&1") == 0
## AssertionError

can you help me to fix this? thanks.

**Comment by limeless** [comment]
I tried the manual install via download github version and install.
the same error came up again.
*cause the log is too long so I paste it on gist.
https://gist.github.com/limeless/f18994650705618e7b29
here is all I have. please help me to figure how Ive done wrong.

**Comment by DTVD** [comment]
Hello @limeless. Thanks for report.

Can you provide output of following commands ?
```bash
cc -fPIC -shared -o
which cc
whereis cc
```

**Comment by limeless** [comment]
@DTVD  Thanks for quick reply!
here is the result 

--
Last login: Tue Jan 13 23:06:36 on ttys000
BendeMacBook-Pro:~ z3roblock$ cc -fPIC -shared -o
clang: error: argument to '-o' is missing (expected 1 value)
clang: error: no input files
BendeMacBook-Pro:~ z3roblock$ which cc
/usr/bin/cc
BendeMacBook-Pro:~ z3roblock$ whereis cc
/usr/bin/cc
BendeMacBook-Pro:~ z3roblock$

**Comment by DTVD** [comment]
I'm sorry can we continue with following command ?
``` bash
cd /Users/z3roblock/venv/lib/python2.7/site-packages/rainbowstream/
ls image.c
cc -fPIC -shared -o ~/.image.so image.c
ls -la ~/.image.so
```

**Comment by limeless** [comment]
sure !
```
BendeMacBook-Pro:~ z3roblock$ cd /Users/z3roblock/venv/lib/python2.7/site-packages/rainbowstream/
BendeMacBook-Pro:rainbowstream z3roblock$ ls image.c
image.c
BendeMacBook-Pro:rainbowstream z3roblock$ cc -fPIC -shared -o ~/.image.so image.c
BendeMacBook-Pro:rainbowstream z3roblock$ ls -la ~/.image.so
-rwxr-xr-x  1 z3roblock  staff  8576 Jan 14 01:33 /Users/z3roblock/.image.so
BendeMacBook-Pro:rainbowstream z3roblock$
```

**Comment by DTVD** [comment]
Hmm everything seem fine. This is really strange. 

Can you change the file 
`/Users/z3roblock/venv/lib/python2.7/site-packages/rainbowstream/image.c` 
like following
![diff](http://i.gyazo.com/a7bb94f70820497622463a621a083fae.png)

and start `rainbowstream again to see the result ?`

**Comment by limeless** [comment]
Im not really sure where to modify in this file,
file looks like nothing similar than yours,,,
![screen shot 2015-01-14 at 5 01 07 pm](https://cloud.githubusercontent.com/assets/1501022/5736283/0cb8cd18-9c0f-11e4-8a03-672e709ae5a5.png)

**Comment by limeless** [comment]
Can I ask a question outside the topic?
what terminal did you use for demos?
really love the information output at the bottom. :+1:

**Comment by limeless** [comment]
OK I finally realise it's c_image.py to change.
now rainbowstream is working flawless.

thanks a lot for your help!!

**Comment by DTVD** [comment]
Sorry it's my fault in mentioning `image.c`. It was `c_image.py`
So what was the problem ?

FYI the demo terminal is just MacOSX default one. The bottom line is [power line](https://github.com/powerline/powerline)

**Comment by limeless** [comment]
After I modify c_image.py like your picture.
I can startup rainbowstream with no error message,
all function is working *tested -iot 
but I didn't know how this little modify can make this work.

**Comment by DTVD** [comment]
I just wanted to see the result of `print(os.system(cmd))`.
When you run RS did you notify any output before the ascii art ?

**Comment by limeless** [comment]
currently Im away from my Mac so I open this on Putty.
here is the result.
![image](https://cloud.githubusercontent.com/assets/1501022/5865927/f2155c0a-a2c7-11e4-8e39-7c5fe5c4f806.png)

sorry about the late reply, currently on new year vacation.

**Comment by DTVD** [comment]
Seems that nothing is printed out.... I will try to cover this problem in next release. Thanks for report :+1:

**Comment by verma007piyush** [comment]
Hi guys,
Facing problems in setting it up in ubuntu....getting the following error:

We have connection problem with twitter REST API right now :(
Error 32: Could not authenticate you.
